"""
Tools for Vapi agent operations.

Provides utilities for:
- Template interpolation
- Field provenance marking
- Configuration assembly
"""

import json
import re
from re import Match
from typing import Any


def interpolate_template(template: dict | list | str, context: dict[str, Any]) -> Any:
    """
    Recursively interpolate template placeholders with context values.

    Placeholders are in the format: {{variable_name}}

    Args:
        template: Template data (dict, list, or string)
        context: Dictionary of values to substitute

    Returns:
        Interpolated template with placeholders replaced
    """
    if isinstance(template, dict):
        return {key: interpolate_template(value, context) for key, value in template.items()}
    elif isinstance(template, list):
        return [interpolate_template(item, context) for item in template]
    elif isinstance(template, str):
        return _interpolate_string(template, context)
    else:
        return template


def _interpolate_string(text: str, context: dict[str, Any]) -> str:
    """
    Interpolate placeholders in a string.

    Args:
        text: String with placeholders
        context: Values to substitute

    Returns:
        String with placeholders replaced
    """

    def replace_placeholder(match: Match[str]) -> str:
        placeholder = match.group(1)
        if placeholder in context:
            value = context[placeholder]
            # Convert to string, handling special types
            if isinstance(value, (list, dict)):
                return json.dumps(value)
            return str(value)
        # Leave unmatched placeholders as-is for error detection
        return match.group(0)

    pattern = r"\{\{([^}]+)\}\}"
    return re.sub(pattern, replace_placeholder, text)


def mark_field_provenance(
    config: dict[str, Any], intake: dict[str, Any]
) -> dict[str, dict[str, str]]:
    """
    Mark the provenance of each field in the generated configuration.

    Provenance categories:
    - copied: Directly copied from intake
    - derived: Computed from intake fields
    - inferred: Generated by model or logic
    - defaulted: Default value from template

    Args:
        config: Generated configuration
        intake: Original intake data

    Returns:
        Dictionary mapping field paths to provenance metadata
    """
    provenance: dict[str, dict[str, str]] = {}

    # Top-level fields
    if "name" in config:
        # Name is derived from organization display name
        provenance["name"] = {"type": "derived", "source": "intake.business_name"}

    if "model" in config:
        # Model config is from template
        provenance["model"] = {"type": "defaulted", "source": "template"}

    if "voice" in config:
        voice_id = config.get("voice", {}).get("voiceId")
        if voice_id and intake.get("vapi", {}).get("voice_id") == voice_id:
            provenance["voice.voiceId"] = {"type": "copied", "source": "intake.vapi.voice_id"}
        else:
            provenance["voice"] = {"type": "defaulted", "source": "template"}

    if "serverUrl" in config:
        # Server URL is from intake
        provenance["serverUrl"] = {"type": "copied", "source": "intake.vapi.server_url"}

    if "firstMessage" in config:
        # First message is derived from organization name
        provenance["firstMessage"] = {"type": "derived", "source": "intake.business_name"}

    if "endCallMessage" in config:
        # End call message is derived from organization name
        provenance["endCallMessage"] = {"type": "derived", "source": "intake.business_name"}

    if "tools" in config:
        # Tools are filtered based on capabilities
        provenance["tools"] = {"type": "derived", "source": "intake.capabilities"}

    if "metadata" in config:
        metadata = config.get("metadata", {})
        if "organization_id" in metadata:
            provenance["metadata.organization_id"] = {
                "type": "copied",
                "source": "intake.organization_id",
            }
        if "capabilities" in metadata:
            provenance["metadata.capabilities"] = {
                "type": "copied",
                "source": "intake.capabilities",
            }

    # Default for other fields
    for key in config:
        if key not in provenance:
            # Check if it came from intake
            if _field_in_intake(key, config[key], intake):
                provenance[key] = {"type": "copied", "source": "intake"}
            else:
                provenance[key] = {"type": "defaulted", "source": "template"}

    return provenance


def _field_in_intake(field_name: str, field_value: Any, intake: dict[str, Any]) -> bool:
    """
    Check if a field value appears in intake data.

    Args:
        field_name: Name of the field
        field_value: Value to search for
        intake: Intake data

    Returns:
        True if value found in intake
    """

    # Simple check - can be enhanced with deeper search
    def search_dict(d: dict, value: Any) -> bool:
        for v in d.values():
            if v == value:
                return True
            if isinstance(v, dict) and search_dict(v, value):
                return True
        return False

    return search_dict(intake, field_value)


def assemble_config(
    interpolated_config: dict[str, Any], organization_id: str, capabilities: list
) -> dict[str, Any]:
    """
    Assemble final configuration with metadata and validation.

    Args:
        interpolated_config: Configuration with placeholders filled
        organization_id: Organization identifier
        capabilities: List of enabled capabilities

    Returns:
        Complete configuration ready for validation and deployment
    """
    # Ensure metadata section exists
    if "metadata" not in interpolated_config:
        interpolated_config["metadata"] = {}

    # Add/update metadata
    interpolated_config["metadata"]["organization_id"] = organization_id
    interpolated_config["metadata"]["capabilities"] = capabilities
    interpolated_config["metadata"]["template_version"] = "1.0.0"
    interpolated_config["metadata"]["created_by"] = "agent-forge"

    # Ensure required fields exist
    if "recordingEnabled" not in interpolated_config:
        interpolated_config["recordingEnabled"] = True

    if "hipaaEnabled" not in interpolated_config:
        interpolated_config["hipaaEnabled"] = False

    # Validate tool references match capabilities
    if "tools" in interpolated_config:
        interpolated_config["tools"] = [
            tool
            for tool in interpolated_config["tools"]
            if _tool_capability_matches(tool, capabilities)
        ]

    return interpolated_config


def _tool_capability_matches(tool: dict[str, Any], capabilities: list) -> bool:
    """
    Check if a tool matches the enabled capabilities.

    Args:
        tool: Tool definition
        capabilities: List of capability names

    Returns:
        True if tool should be included
    """
    # Extract tool name
    tool_name = tool.get("function", {}).get("name", "")

    # Map tool names to capabilities
    tool_capability_map = {
        "check_availability": "availability",
        "book_appointment": "booking",
        "cancel_appointment": "cancellation",
        "reschedule_appointment": "rescheduling",
    }

    required_capability = tool_capability_map.get(tool_name)
    if not required_capability:
        return True  # Unknown tools are included by default

    return required_capability in capabilities


def extract_tool_references(config: dict[str, Any]) -> list[str]:
    """
    Extract all tool IDs referenced in the configuration.

    Args:
        config: Assistant configuration

    Returns:
        List of tool IDs
    """
    tool_ids = []

    tools = config.get("tools", [])
    for tool in tools:
        if "id" in tool:
            tool_ids.append(tool["id"])
        elif "function" in tool and "name" in tool["function"]:
            tool_ids.append(tool["function"]["name"])

    return tool_ids


def validate_placeholder_resolution(config: dict[str, Any]) -> list[str]:
    """
    Check for any unresolved placeholders in the configuration.

    Args:
        config: Configuration to check

    Returns:
        List of unresolved placeholder names
    """
    unresolved = []
    config_str = json.dumps(config)

    pattern = r"\{\{([^}]+)\}\}"
    matches = re.finditer(pattern, config_str)

    for match in matches:
        placeholder = match.group(1)
        # Exclude known runtime placeholders that should remain
        if placeholder not in ["WEBHOOK_SECRET"]:
            unresolved.append(placeholder)

    return unresolved


def sanitize_config_for_validation(config: dict[str, Any]) -> dict[str, Any]:
    """
    Sanitize configuration for validation by removing sensitive fields.

    Args:
        config: Configuration to sanitize

    Returns:
        Sanitized configuration
    """
    sanitized = config.copy()

    # Remove or mask sensitive fields
    if "serverUrlSecret" in sanitized:
        sanitized["serverUrlSecret"] = "{{WEBHOOK_SECRET}}"  # Keep as placeholder

    # Ensure no API keys are present
    sensitive_keys = ["apiKey", "api_key", "secret", "password", "token"]
    for key in sensitive_keys:
        if key in sanitized:
            del sanitized[key]

    return sanitized
