-- Migration: 004_task_executions.sql
-- Create TaskExecution table for specialist delegations

-- Create task status enum
CREATE TYPE task_status AS ENUM (
    'pending',
    'running',
    'success',
    'validation_failed',
    'error',
    'blocked',
    'aborted'
);

-- TaskExecution table: one deterministic delegation to a specialist domain
CREATE TABLE task_executions (
    task_id TEXT PRIMARY KEY,
    deployment_id UUID NOT NULL REFERENCES deployments(deployment_id),
    session_id UUID NOT NULL REFERENCES sessions(session_id),
    agent_target TEXT NOT NULL,
    action_type TEXT NOT NULL,
    context_hash TEXT NOT NULL,
    constraints JSONB NOT NULL DEFAULT '[]',
    dependency_task_ids JSONB NOT NULL DEFAULT '[]',
    verification_required BOOLEAN NOT NULL DEFAULT true,
    status task_status NOT NULL DEFAULT 'pending',
    attempt_number INTEGER NOT NULL DEFAULT 1 CHECK (attempt_number > 0),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_class failure_class,
    error_detail TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Constraint: agent_target cannot change after creation (enforce in application)
-- This is a logical constraint enforced by application code, not a DB constraint

-- Check constraint: completed_at only for terminal states
ALTER TABLE task_executions ADD CONSTRAINT task_executions_completed_at_terminal
    CHECK (
        (status IN ('success', 'validation_failed', 'error', 'aborted')
         AND completed_at IS NOT NULL) OR
        (status NOT IN ('success', 'validation_failed', 'error', 'aborted')
         AND completed_at IS NULL)
    );

-- Check constraint: error_class only for error states
ALTER TABLE task_executions ADD CONSTRAINT task_executions_error_class_on_error
    CHECK (
        (status IN ('error', 'validation_failed') AND error_class IS NOT NULL) OR
        (status NOT IN ('error', 'validation_failed') AND error_class IS NULL)
    );

-- Indexes for queries
CREATE INDEX task_executions_deployment_id_idx ON task_executions(deployment_id, created_at);
CREATE INDEX task_executions_status_idx ON task_executions(status);
CREATE INDEX task_executions_agent_target_idx ON task_executions(agent_target);

-- Comments
COMMENT ON TABLE task_executions IS 'Specialist agent task delegations with dependencies';
COMMENT ON COLUMN task_executions.task_id IS 'Generated by application, deterministic format';
COMMENT ON COLUMN task_executions.agent_target IS 'Must exist in agent registry, immutable after creation';
COMMENT ON COLUMN task_executions.context_hash IS 'SHA-256 of sanitized immutable context';
COMMENT ON COLUMN task_executions.dependency_task_ids IS 'Array of prior task IDs that must be satisfied';
COMMENT ON COLUMN task_executions.attempt_number IS 'Attempt number for this task (starts at 1)';
