"""
Unit tests for orchestrator/action_builder.py.

This logic previously lived on FullOrchestrator, which no test referenced, so
it shipped uncovered. These tests pin the action set each intake shape produces
and the safety metadata each action carries.
"""

from typing import Any

import pytest

from orchestrator.action_builder import build_onboarding_actions
from orchestrator.assembler import DeploymentPackage
from shared.result_object import ResultObject

pytestmark = pytest.mark.unit


def _artifact(agent_source: str) -> ResultObject:
    return ResultObject(
        task_id=f"task-{agent_source}",
        agent_source=agent_source,
        content_hash="a" * 64,
        storage_path=f"outputs/test_org/{agent_source}/config.json",
        summary=f"Generated by {agent_source}",
        field_provenance={},
        model_id=None,
        validation_status="verified",
    )


def _package(*agent_sources: str) -> DeploymentPackage:
    return DeploymentPackage(
        deployment_id="dep-001",
        organization_id="test_org",
        is_complete=True,
        validation_passed=True,
        artifacts=[_artifact(s) for s in agent_sources],
        manifest={},
        errors=[],
    )


def _intake(**overrides: Any) -> dict[str, Any]:
    base: dict[str, Any] = {
        "organization_id": "test_org",
        "business_name": "Test Biz",
        "timezone": "America/New_York",
        "enabled_capabilities": ["booking"],
        "hosting": {"webhook_base_url": "https://example.invalid"},
    }
    base.update(overrides)
    return base


def _ops(actions: list) -> list[tuple[str, str]]:
    return [(a.platform, a.operation) for a in actions]


class TestActionSet:
    def test_booking_intake_produces_full_action_set(self) -> None:
        actions = build_onboarding_actions(_package("vapi_agent"), _intake())

        assert _ops(actions) == [
            ("supabase_client", "insert_org_record"),
            ("vapi", "create_assistant"),
            ("make", "create_scenario"),
            ("render", "set_env_variable"),
            ("render", "trigger_deploy"),
        ]

    def test_org_record_only_created_for_booking(self) -> None:
        actions = build_onboarding_actions(
            _package("vapi_agent"), _intake(enabled_capabilities=["availability"])
        )
        assert ("supabase_client", "insert_org_record") not in _ops(actions)

    def test_no_vapi_artifact_means_no_assistant_action(self) -> None:
        actions = build_onboarding_actions(_package("make_agent"), _intake())
        assert ("vapi", "create_assistant") not in _ops(actions)

    def test_one_make_scenario_per_supported_capability(self) -> None:
        actions = build_onboarding_actions(
            _package("vapi_agent"),
            _intake(enabled_capabilities=["booking", "cancellation", "rescheduling"]),
        )
        scenarios = [a for a in actions if a.operation == "create_scenario"]
        assert len(scenarios) == 3
        assert {a.target for a in scenarios} == {
            "scenario/test_org/booking",
            "scenario/test_org/cancellation",
            "scenario/test_org/rescheduling",
        }

    def test_unsupported_capability_produces_no_scenario(self) -> None:
        actions = build_onboarding_actions(
            _package("vapi_agent"), _intake(enabled_capabilities=["smalltalk"])
        )
        assert not [a for a in actions if a.operation == "create_scenario"]

    def test_render_actions_skipped_without_webhook_base_url(self) -> None:
        actions = build_onboarding_actions(_package("vapi_agent"), _intake(hosting={}))
        assert not [a for a in actions if a.platform == "render"]

    def test_empty_intake_capabilities_yields_no_actions(self) -> None:
        actions = build_onboarding_actions(_package(), _intake(enabled_capabilities=[], hosting={}))
        assert actions == []


class TestActionSafetyMetadata:
    def test_every_action_carries_a_proposal_hash(self) -> None:
        actions = build_onboarding_actions(_package("vapi_agent"), _intake())
        assert all(a.proposal_hash for a in actions)
        # Distinct actions must not collide, or approval could be replayed
        # against a different operation.
        hashes = [a.proposal_hash for a in actions]
        assert len(set(hashes)) == len(hashes)

    def test_destructive_creates_have_compensation_operations(self) -> None:
        actions = build_onboarding_actions(_package("vapi_agent"), _intake())
        by_op = {a.operation: a for a in actions}

        assert by_op["insert_org_record"].compensation_operation == "delete_org_record"
        assert by_op["create_assistant"].compensation_operation == "delete_assistant"
        assert by_op["create_scenario"].compensation_operation == "delete_scenario"
        assert by_op["set_env_variable"].compensation_operation == "delete_env_variable"

    def test_non_idempotent_creates_are_not_marked_retryable(self) -> None:
        actions = build_onboarding_actions(_package("vapi_agent"), _intake())
        by_op = {a.operation: a for a in actions}

        # Creating an assistant or scenario twice makes a duplicate, so these
        # must never be auto-retried.
        assert by_op["create_assistant"].retry_policy == "none"
        assert by_op["create_scenario"].retry_policy == "none"
        assert by_op["insert_org_record"].retry_policy == "proven_idempotent"
        assert by_op["set_env_variable"].retry_policy == "proven_idempotent"

    def test_onboarding_actions_carry_no_state_version(self) -> None:
        # Onboarding is all creates, so there is no prior state to be stale
        # against. Updates are the case that needs a state_version.
        actions = build_onboarding_actions(_package("vapi_agent"), _intake())
        assert all(a.state_version is None for a in actions)


class TestVapiAssistantActionCarriesPhoneNumber:
    """A live onboarding created an assistant nobody could call.

    `phone_number_id` was absent from the payload, so the assignment branch in
    the orchestrator never fired and the number stayed pointed at the previous
    assistant — while the action reported success.
    """

    def test_phone_number_id_is_taken_from_intake(self) -> None:
        intake = _intake(
            external_identifiers={"vapi_phone_number_id": "ca649cc0-1234"},
        )
        actions = build_onboarding_actions(_package("vapi_agent"), intake)
        vapi = next(a for a in actions if a.operation == "create_assistant")

        assert vapi.payload["phone_number_id"] == "ca649cc0-1234"

    def test_expected_outcome_names_tools_and_phone(self) -> None:
        """The operator approves this text, so it must describe every side effect."""
        intake = _intake(external_identifiers={"vapi_phone_number_id": "ca649cc0-1234"})
        actions = build_onboarding_actions(_package("vapi_agent"), intake)
        vapi = next(a for a in actions if a.operation == "create_assistant")

        assert "tools" in vapi.expected_outcome
        assert "ca649cc0-1234" in vapi.expected_outcome

    def test_absent_phone_number_is_none_not_missing(self) -> None:
        actions = build_onboarding_actions(_package("vapi_agent"), _intake())
        vapi = next(a for a in actions if a.operation == "create_assistant")

        assert vapi.payload["phone_number_id"] is None
        assert "phone number" not in vapi.expected_outcome
